server.port=8080

spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASS:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

## Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

jwt.secret.key=${JWT_SECRET_KEY:dGVzdF9zZWNyZXRfa2V5X2Zvcl90ZXN0aW5nX29ubHk}
# 1h in millisecond
jwt.expiration=3600000

# Email Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:test}
spring.mail.password=${MAIL_PASSWORD:test}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

